.\" @(#) splotch.1 2.1 sysadm@sparky.phy.queensu.ca 01/04/93
.TH SP_BM 1 "April 1, 1993" "Version 2.1" "sPLOTch! DRIVERS"
.SH NAME
sp_bm - convert sdvi output to bitmap/pixmap formats
.SH SYNOPSIS
.B sp_bm
[
.I options
] [
.I filename
]
.SH DESCRIPTION
.LP
.B
sp_bm
reads the sdvi file
.I filename
produced by the sPLOTch! program
and produces a bitmap or pixmap which corresponds to the indicated output.  
This
bit/pixmap can be exported in a variety of standard file formats, including
several formats suitable for printing on dot matrix or other bit/pixmap
based printers.  For lack of a better place to go, the output is sent by
default to the standard output,
although it can be redirected into a file or be sent directly to a printer.
If no 
.I filename
is given,
.I sp_ps
reads the sdvi information from the standard input (for use as a direct
output driver).
.SH OPTIONS
.TP
.B -d depth
Specifies the colour/grey depth of the pixmap.  For greyscale pixmaps,
the
.I depth
is the number of bits associated with each pixel (monochrome bitmaps are
one bit deep).  For colour pixmaps, the
.I depth
is the number of bits for each colour (red, green and blue) associated
with each pixel.  Note: depending on the format type, the depth may be
adjusted upwards to legal values (see below).
.TP
.B -D
Requests that the output be internally rendered with a 
.I depth
of 8, and then be dithered down to the specified final depth 
(-d option) using Floyd-Steinberg error diffusion.  This may give better
results than the default usage of ordered dithering patterns, however,
it is more memory intensive.  Specifying this option will disable the
ordered dithering process by setting the dither resolution (-n option) to zero.
.TP
.B -e dimension
Specifies the spatial extent (size) of the bit/pixmap.  The
.I dimension
argument can take two forms: a single value, or a pair of values
separated by the 'x' character (ie.
.I 720x360
).  In the latter case, the two values respectively represent the x and
y bit/pixmap dimensions, in dots.  If only one value is given,
it is used for both x and y dimensions.  How the final sdvi output appears
in the bit/pixmap depends on the specification of this option and the
resolution (-r) option.  If the resolution is not specified, the sdvi
output is scaled according to the absolute page dimension to fit the
specified dimensions (the bit/pixmap is output at the default format
resolution).  Otherwise, the output is processed normally, and may not
fit the specified bit/pixmap dimensions.  Any output outside of the
active area will be clipped.  If the dimension is not specified, the
final bit/pixmap size is determined by the absolute page size provided
by sPLOTch!
Note: depending on the format type, the
dimensions may be adjusted upwards to legal values (see below).
.TP
.B -f format
Specifies the format of the final bit/pixmap.  The available format
types, as well as the default and legal parameters associated with these
formats, are listed below.
.TP
.B -g
Forces the conversion of all colour information into a corresponding
greyscale intensity, via the YIQ colour conversion matrix 
(the Y component is used as
the grey intensity, see an appropriate graphics text for further
information).  Pixmap formats which are greyscale by design perform this
conversion automatically.  This option is overridden by the -m option
below.
.TP 
.B -h
Prints out a short help file of the options available and any defined
defaults, as well as a list of available output formats.
.TP
.B -m
Forces all colour or greyscale output to be displayed using monochrome
halftone shading (black and white only).  Essentially, this is just a
shortcut to specifying the grey (-g) option with a depth (-d) of one.
This option is automatically set 
for all bitmap formats, which are monochrome by default.
.TP
.B -n value
Specifies the resolution of the ordered dithering pattern used to
quantize colour/grey intensity values down to the specified depth of the
bit/pixmap.  The 
.I value
represents the number of intermediate shades which are available, and
can take one of three values: 0 (no dithering), 16 or 64.  Higher
dithering resolutions will give better results, but at a cost of
computational complexity.  The default setting is format dependent, and
is chosen to give at least 256 total intensity shades.  Note: this
option is forced to 0 (no dithering) if the -D option is specified.
.TP
.B -o name
Outputs the bit/pixmap information into the specified file
.I name.
Use of this option overrides the specification of the direct printer
name via the -P option.  If a minus sign (-) is given as the output
filename, the bit/pixmap output is dumped to the standard output
channel.
.TP
.B -P name
Outputs the bit/pixmap information to the specified printer
.I name.
If a minus sign (-) is given as the printer name, the bit/pixmap output
is dumped to the standard error channel.  If no printer name is given,
and no output file is specified using the -o option, the output is sent to
the standard output, as it is difficult to determine an appropriate
destination by default.
.TP
.B -r resolution
Specifies the spatial resolution of the bit/pixmap.  The
.I resolution
argument can take two forms: a single value, or a pair of values
separated by the 'x' character (ie.
.I 30x60
).  In the latter case, the two values respectively represent the x and
y bit/pixmap resolutions, in dots per inch.  If only one value is given,
it is used for both x and y resolutions.  The default resolution is
dependent on the specified format type.
.TP
.B -s
Prints the sdvi output in landscape orientation (sideways).  Default
page sizes in
.I splotch
assume portrait orientation, but certain output sizes lend themselves to
landscape.  Note: this option is not to be confused with the 
.B rotate
setting in sPLOTch!,
which has the same effect but in a completely different fashion.
.SH FORMATS
.LP
Here are the valid set of bit/pixmap output formats (-f option).  Also listed
are the valid resolutions (-r option) and depths (-d option), as well
as the possible visual types (colour, grey or mono).  All default
values are either listed as such or indicated by an asterisk (*).  Note:
some of these output formats may not be available, as they can be
disabled at the time of compilation.

.SH EXAMPLE USAGE
.LP
splotch <splotch_file> -d 'sp_bm -f epson -r 72x72 -Plp'
.SH AUTHOR
.LP
Jeff Heisz
.SH "SEE ALSO"
splotch(1)

.I sPLOTch! Users Guide

.I sPLOTch! Language Reference
.SH FILES
.LP
None (except for the input file).
.SH BUGS
.LP
