
/******************************************************************
                          sPLOTch!

  Spoof.h - the character strings defining the output messages 
	    for the error description set.  Should be in spastic.h,
	    but causes errors due to multiple definition.

*******************************************************************/      

char *errs[]={                     /* standard error messages */
"Huh? Error routine called for an unknown error type.",
"Unrecognized command.",
"Text string missing closing quote.",
"Unknown font name.",
"Move or Draw requires both an x and y coordinate.",
"Size specification improper or not allowed in this context.",
"Invalid command in current context.",
"Axis specifier limited to 1 through 20.",
"Hi to you too!",
"Command argument missing or improperly specified.",
"Unable to open this input (or output) file.",
"No input variables specified.",
"Range specification must have at least two values.",
"No data available in current file to input.",
"Number of variables does not match input file data format.",
"Axis is undefined.",
"Offset must be specified for both ends of the axis.",
"Title or Footnote specifier limited to [1] through 10.",
"Plot format must be of the form y(x) or z(x,y) [post variables].",
"Variable undefined (no associated data).",
"Symbol specifier limited to [0] through 100.",
"Bad curve fitting specification.",
"Data set specification limited to [1] through 10.",
"Bad line type.",
"Invalid device type.",
"Warning: Setting ignored due to device already being set.",
"No input or output file has been opened.",
"Incorrect number of variables for surface or boundary specification.",
"Range list truncated at 100 terms.",
"Histogram output requires 2 variables.",
"No PostScript file stream opened.",
"PostScript input file not of proper EPS format.",
"Unable to open requested input file.",
"Input file tree overflow (too many nested input calls).",
"Bad output list.  Two variables not given or out of memory.",
"No output variables defined for processing data.",
"Improper number of variables to define error data.",
"Location of severe error occurence (approximate).",
"Improper number of coordinates (usually three).",
"Bad layout parameter - must be octal.",
"Mismatched grouping brackets.  No matching open for this close.",
"Bad pattern number or no pattern defined for this value.",
"Improper colour specification.",
"Special value illegal or out of range (0-9).",
"Bracket mismatch - no close for this opening bracket.",
"Missing variable, function or number (in this area).",
"Bad special variable specification (@@a - @@z).",
"Bad function specification.",
"Function argument missing or has improper number of elements.",
"Bad variable range specification.",
"Undefined data set (no associated data).",
"Unable to connect to external process (bad shell?).",
"Too many input/output variables given at once.",
"Too many reference lines (limited to 40 total).",
"Bad clipping type.",
"Bad polar angle unit specification (degree, radian or gradian).",
"Precision specification is either 'single' or 'double'.",
"Arrow types are either 'open' or 'close'.",
"Maximum of 10 surfaces (contours, histograms) allowed.",
"Arrow parameter is either 1 (left), 2 (right) or 3 (both).",
"Surface type must be 'either', 'grid' or 'triangle'.",
"Macro names to be defined must be enclosed in parentheses.",
"Bad if-then-else structure - extra else's, no if for endif or bad nesting.",
"Invalid horizontal origin alignment - use left, right or center.",
"Invalid vertical origin alignment - use top, bottom or center.",
"Error log output can either be turned 'on' or 'off'.",
"Bad nesting of loops and/or if statements (endloop inside another type).",
"Invalid FOR loop specification (v=start,end,step) or invalid variable.",
"Invalid FOREACH loop specification (variable, entry list).",
"4dsurface or 4dcontour plots require auxiliary data, ie. z(x,y)[aux].",
"Improper 3d transformation type.",
"Hey! Only one surface at a time please.",
"Bad hidden edge specification - use byshade, byhorizon or none."
};

char *svrs[]={                    /* fatal error messages */
"Huh? Severe error routine called with invalid error type.",
"Temporary buffer overflow during command parsing.",
"Termination due to error count overflow.",
"Data storage overflow.  Too many data subsets.",
"Too many coordinate sets for plotting.",
"No memory available for spline fitting.",
"Severe internal failure-unexplained.",
"Too many grid points in x or y base (contour or 3d).",
"Data input space overflowed (too many points).",
"Contour path length exceeds preset limit.",
"Too many layers in text commands. (limit 20)",
"Broken pipe.  Premature exit of data processing command or device driver.",
"Cannot nest loops or if statements deeper than 40 levels.",
"Too many data curves in single variable specification.",
"Macro definition overflow - too many macros defined."
};
